In [32]:
import numpy as np
import scipy.linalg as LA

#from AW_FD import apGrad, apHess, apJacobian
def apGrad( f, x ):
    assert( type(x) is np.ndarray ), 'x debe ser numpy.array'
    
    if len(x.shape)==2:
        x=x[:,0]
    
    n=len(x)
    #Id=np.eye(n)
    #np.finfo(float).eps
    hs=np.diag((np.finfo(float).eps**(1.0/3))*(abs(x)+1))
    
    g=np.zeros((n,1))
    for i in range(n):
        g[i]=0.5*(f(x+hs[:,i])-f(x-hs[:,i]))/hs[i,i]
    return g


def apJacobian( f, x ):
    """f: Rn->Rm"""
    assert( type(x) is np.ndarray ), 'x debe ser numpy.array'
    
    if len(x.shape)==2:
        x=x[:,0]
    
    n=len(x)
    m=len(f(x))
    #Id=np.eye(n)
    #np.finfo(float).eps
    hs=np.diag((np.finfo(float).eps**(1.0/3))*(abs(x)+1))
    
    jac=np.zeros((m,n))
    for j in range(n):
        jac[:,j]=0.5*(f(x+hs[:,j])-f(x-hs[:,j]))/hs[j,j]
    
    
        
    return jac


def apHess( f, x ):
    assert( type(x) is np.ndarray ), 'x debe ser numpy.array'
     
    if len(x.shape)==2:
        x=x[:,0]
    
    n=len(x)
    #Id=np.eye(n)
    #np.finfo(float).eps
    hs=np.diag((np.finfo(float).eps**(1.0/4))*(abs(x)+1))
    
    Hf=np.zeros((n,n))
    for i in range(n):
        for j in range(n):
            Hf[i,j]=0.25*(f(x+hs[:,i]+hs[:,j])\
                          -f(x-hs[:,i]+hs[:,j])\
                          -f(x+hs[:,i]-hs[:,j])\
                          +f(x-hs[:,i]-hs[:,j]))/(hs[i,i]*hs[j,j])
    return Hf



In [18]:
x=np.random.rand(5)
y=np.ones((5,1)).T
np.shape(y)
#y+np.diag((np.finfo(float).eps**(1.0/3))*(abs(x)+1))[:,0]

(1, 5)

### Test: Gradient + Hessian

In [21]:
#np.finfo(float).eps
v = np.array([[1,2,3]]).T
max(v.shape)

3

In [28]:
A = LA.pascal(5).astype(float)
b = -np.ones(5)
f  = lambda x:  0.5*np.dot(x, A@x) + np.dot(b,x)
Df = lambda x:  (0.5*(A+A.T)@x + b)[:,np.newaxis]


In [31]:
# prueba
#x = np.array([1,0,0,0])
x = 5*np.ones(5)
g = apGrad(f, x)
H = apHess(f, x)

#print(A)

gexa = Df(x)
Hexa = A
print('gradient (rel. error): ', (g-gexa)/(abs(gexa)+1) )
print(H-Hexa)


[[ 1.  1.  1.  1.  1.]
 [ 1.  2.  3.  4.  5.]
 [ 1.  3.  6. 10. 15.]
 [ 1.  4. 10. 20. 35.]
 [ 1.  5. 15. 35. 70.]]
gradient (rel. error):  [[2.10354045e-10]
 [1.32755910e-10]
 [3.90639343e-11]
 [3.92934193e-12]
 [2.34230977e-13]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Test: Jacobian

In [33]:
A = LA.pascal(4).astype(float)[0:3,:]
h = lambda x:  A@x

x0 = np.ones(4)
print(A)
apJacobian(h, x0)


[[ 1.  1.  1.  1.]
 [ 1.  2.  3.  4.]
 [ 1.  3.  6. 10.]]


array([[ 1.,  1.,  1.,  1.],
       [ 1.,  2.,  3.,  4.],
       [ 1.,  3.,  6., 10.]])